spring:
  application:
    name: project-yml

server:
  port: 8080

  # Database configuration
  mongodb:
    host: localhost
    port: 27017
    database: ejemplo01
    #username: myuser
    #password: mypassword
  data:
    mongodb:
      auto-index-creation: true